# SPDX-License-Identifier: MIT-0
---
# tasks file for rpmfusion

- name: Install distribution GPG keys package
  ansible.builtin.dnf:
    name: "{{ gpg_keys_package }}"
    state: present

- name: Install RPM Fusion 'free' gpg key
  ansible.builtin.rpm_key:
    key: "{{ rmpfusion_free_rpmkey_path }}"
    state: present

- name: Download RPM Fusion 'free' repository package
  ansible.builtin.get_url:
    url: "{{ rmpfusion_free_repo_url }}"
    dest: "{{ rmpfusion_free_package_dst }}"

- name: Install RPM Fusion 'free' repository
  ansible.builtin.dnf:
    name: "{{ rmpfusion_free_package_dst }}"
    state: present

- name: Install RPM Fusion 'nonfree' gpg key
  ansible.builtin.rpm_key:
    key: "{{ rmpfusion_nonfree_rpmkey_path }}"
    state: present

- name: Download RPM Fusion 'nonfree' repository package
  ansible.builtin.get_url:
    url: "{{ rpmfusion_nonfree_repo_url }}"
    dest: "{{ rmpfusion_nonfree_package_dst }}"

- name: Install RPM Fusion 'nonfree' repository
  ansible.builtin.dnf:
    name: "{{ rmpfusion_nonfree_package_dst }}"
    state: present
