FROM registry.fedoraproject.org/fedora:42

ENV pip_packages="ansible"

# Install requirements.
RUN dnf -y upgrade \
    && dnf -y install python3 python3-pip python3-libdnf5 \
    && dnf clean all

# Upgrading pip
RUN python -m pip install --upgrade pip

# Install Ansible via Pip.
RUN python -m pip install $pip_packages

# Run the command
CMD ["/bin/bash"]
