---
- name: Verify
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Install a package from the free repository
      ansible.builtin.package:
        name: rpmfusion-free-release-tainted
        state: present
